#!/usr/bin/env bash

DYNAMIC=false

if [[ $DYNAMIC = true ]]; then
    DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD' | cut -d':' -f2 | sed -e 's/^ *//g' -e 's/ *$//g')
else
    DEFAULT_BRANCH='master'
fi

# ---------------------------------------------------------------------------------------- #
# Description                                                                              #
# ---------------------------------------------------------------------------------------- #
#                                                                                          #
# ---------------------------------------------------------------------------------------- #

if branch=$(git rev-parse --abbrev-ref HEAD 2>&1); then
    if [[ "${branch}" = "${DEFAULT_BRANCH}" ]]; then
        echo "You cannot commit to the ${DEFAULT_BRANCH} branch - Aborting!"
        exit 1
    fi
fi

# ---------------------------------------------------------------------------------------- #
# End of Script                                                                            #
# ---------------------------------------------------------------------------------------- #
# This is the end - nothing more to see here.                                              #
# ---------------------------------------------------------------------------------------- #
